stages:
  - lint-build-test

variables:
  DIRECTUS_URL: 'http://mocked-directus.com'
  DIRECTUS_STATIC_TOKEN: 'mock-static-stoken'

lint-build-test:
  stage: lint-build-test
  image: node:20
  before_script:
    - yarn clean
    - yarn install
  script:
    - yarn lint && yarn build && yarn test
  only:
    - branches
    - merge_requests
