stages:
  - lint
  - build
  - test

variables:
  DIRECTUS_URL: 'http://mocked-directus.com'
  DIRECTUS_STATIC_TOKEN: 'mock-static-stoken'

lint:
  stage: lint
  image: node:20
  before_script:
    - yarn clean
    - yarn install
  script:
    - yarn lint
  only:
    - branches
    - merge_requests

build:
  stage: build
  image: node:20
  before_script:
    - yarn clean
    - yarn install
  script:
    - yarn build
  only:
    - branches
    - merge_requests

test:
  stage: test
  image: node:20
  before_script:
    - yarn clean
    - yarn install
  script:
    - yarn test
  only:
    - branches
    - merge_requests
