#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn run build ||
  (
    echo '❌👷🔨❌ Better call Bob... Because your build failed ❌👷🔨❌
            Next build failed: View the errors above to see why.
    '
    false
  )

# If everything passes... Now we can commit
echo '✅✅✅✅ You win this time... I am pushing the branch now. ✅✅✅✅
'